"""rename address

Revision ID: 525babaae54d
Revises: c73fc4d97755
Create Date: 2025-03-27 09:09:26.976565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525babaae54d'
down_revision = 'c73fc4d97755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('location')
