"""rename department

Revision ID: c73fc4d97755
Revises: 25a224aeb176
Create Date: 2025-03-27 09:04:03.028810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73fc4d97755'
down_revision = '25a224aeb176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
   
    # ### end Alembic commands ###
